data <- read.table("household_power_consumption.txt", sep=";", header=TRUE, colClasses = "character")
data$Date <- as.Date(as.character(data$Date),"%d/%m/%Y")
newdata <- subset(data, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02")) 
dateStr=paste(newdata$Date,newdata$Time)
dateTime=strptime(dateStr, "%Y-%m-%d %H:%M:%S")
png(file="plot3.png", width = 480, height = 480)
plot(dateTime,newdata$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
lines(dateTime,newdata$Sub_metering_2,col="red",ylab="Energy sub metering",xlab="")
lines(dateTime,newdata$Sub_metering_3,col="blue",ylab="Energy sub metering",xlab="")
legend("topright",lty="solid",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()