data <- read.table("household_power_consumption.txt", sep=";", header=TRUE, colClasses = "character")
data$Date <- as.Date(as.character(data$Date),"%d/%m/%Y")
newdata <- subset(data, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02")) 
dateStr=paste(newdata$Date,newdata$Time)
dateTime=strptime(dateStr, "%Y-%m-%d %H:%M:%S")
png(file="plot2.png", width = 480, height = 480)
plot(dateTime,newdata$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab="")
dev.off()